# Generated by Django 3.2.9 on 2021-11-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
