# Generated by Django 3.2.9 on 2021-11-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tone',
            name='duan',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tone',
            name='hang',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
