# Generated by Django 3.2.9 on 2021-11-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_auto_20211113_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='tone',
            name='type',
            field=models.CharField(choices=[('五十音', '五十音'), ('浊音', '浊音'), ('半浊音', '半浊音'), ('拗音', '拗音'), ('拨音', '拨音')], default='五十音', max_length=200),
        ),
    ]
