# Generated by Django 3.2.9 on 2021-11-28 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_chapter_grammer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='basic_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='dialog_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tone',
            name='type',
            field=models.CharField(choices=[('五十音', '五十音'), ('浊音', '浊音'), ('半浊音', '半浊音'), ('拗音', '拗音'), ('拨音', '拨音'), ('促音', '促音')], default='五十音', max_length=200),
        ),
    ]
