# Generated by Django 3.2.9 on 2022-05-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0010_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.CharField(default='www.youtube.com', max_length=1000),
        ),
    ]
